# RDS MySQL in the isolated subnets, with its password in Secrets Manager.
#
# The password is generated by an *ephemeral* resource and passed to RDS and
# Secrets Manager through *write-only* arguments. Terraform uses it during the
# apply and then forgets it: it is never written to the state file or shown
# in a plan. To rotate it, bump password_version.

ephemeral "random_password" "db" {
  length = 32
  # RDS refuses / @ " and spaces in the master password.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_db_subnet_group" "this" {
  name       = var.name
  subnet_ids = var.subnet_ids
  tags       = { Name = var.name }
}

resource "aws_db_parameter_group" "this" {
  name   = "${var.name}-mysql${replace(var.engine_version, ".", "")}"
  family = "mysql${var.engine_version}"

  # Refuse any connection that is not encrypted, even from inside the VPC.
  parameter {
    name  = "require_secure_transport"
    value = "1"
  }

  # Log queries slower than one second (to CloudWatch, see below).
  parameter {
    name  = "slow_query_log"
    value = "1"
  }
  parameter {
    name  = "long_query_time"
    value = "1"
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_db_instance" "this" {
  identifier     = var.name
  engine         = "mysql"
  engine_version = var.engine_version
  instance_class = var.instance_class

  db_name             = var.db_name
  username            = var.username
  password_wo         = ephemeral.random_password.db.result
  password_wo_version = var.password_version

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.security_group_id]
  parameter_group_name   = aws_db_parameter_group.this.name
  publicly_accessible    = false
  multi_az               = var.multi_az
  ca_cert_identifier     = "rds-ca-rsa2048-g1"

  storage_type          = "gp3"
  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_encrypted     = true

  backup_retention_period   = var.backup_retention_days
  backup_window             = "17:00-17:30" # 02:00 in Tokyo, when nobody is looking
  maintenance_window        = "sun:18:00-sun:19:00"
  copy_tags_to_snapshot     = true
  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name}-final"

  auto_minor_version_upgrade      = true
  enabled_cloudwatch_logs_exports = ["error", "slowquery"]

  tags = { Name = var.name }
}

resource "aws_secretsmanager_secret" "db" {
  name                    = "${var.name}/db"
  description             = "MySQL login for ${var.name}. ECS reads the password key."
  recovery_window_in_days = var.secret_recovery_days
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string_wo = jsonencode({
    username = var.username
    password = ephemeral.random_password.db.result
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = var.db_name
  })
  secret_string_wo_version = var.password_version
}
